import Head from 'next/head';
import { useContext } from "react";
import { Login } from "./components/Login";
import { Account } from "./components/Account";
import { SinglePay } from "./components/SinglePay";
import { Provider } from "./AppState";

export default function Home() {
  return (
    <Provider>

    <div className="flex flex-col justify-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="bg-red-200 flex flex-row" >
        <div className="flex-grow flex items-center" >
          <Account />
        </div>
        <div className="" >
          <Login />         
        </div>
      </div>

      <main className='p-4'>
        <SinglePay />
      </main>

    </div>
    </Provider>
  )
}
