import Head from 'next/head';
import { useContext } from "react";
import { Login } from "./components/Login";
import { Account } from "./components/Account";
import { SinglePay } from "./components/SinglePay";
import { SinglePayWithClose } from "./components/SinglePayWithClose";
import { Provider } from "./AppState";

export default function Home() {

  const sendCake = async ()=>{
    const data = {
      abc: 123
    };
    const response = await fetch("/api/hello", {
      method: 'POST', // *GET, POST, PUT, DELETE, etc.
      mode: 'cors', // no-cors, *cors, same-origin
      cache: 'no-cache', // *default, no-cache, reload, force-cache, only-if-cached
      credentials: 'same-origin', // include, *same-origin, omit
      headers: {
        'Content-Type': 'application/json'
      },
      redirect: 'follow', // manual, *follow, error
      referrerPolicy: 'no-referrer', // no-referrer, *no-referrer-when-downgrade, origin, origin-when-cross-origin, same-origin, strict-origin, strict-origin-when-cross-origin, unsafe-url
      body: JSON.stringify(data) // body data type must match "Content-Type" header
    });

    const result = await response.json(); // parses JSON response into native JavaScript objects
    console.log(result);
  }

  return (
    <Provider>

    <div className="flex flex-col justify-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="bg-red-200 flex flex-row" >
        <div className="flex-grow flex items-center" >
          <Account />
        </div>
        <div className="" >
          <Login />         
        </div>
      </div>

      <main className='p-4'>
        <SinglePay />
        <SinglePayWithClose />

        <button className='btn btn-sm btn-primary m-4' onClick={sendCake}>Send Cake</button>
      </main>

    </div>
    </Provider>
  )
}
